export enum JourneyStage {
  REGISTERED = 'REGISTERED',
  THEORY_COURSE_IN_PROGRESS = 'THEORY_COURSE_IN_PROGRESS',
  RENACH_PENDING = 'RENACH_PENDING',
  MEDICAL_PENDING = 'MEDICAL_PENDING',
  PSYCH_PENDING = 'PSYCH_PENDING',
  THEORY_EXAM_PENDING = 'THEORY_EXAM_PENDING',
  AWAITING_LADV_UPLOAD = 'AWAITING_LADV_UPLOAD',
  LADV_UPLOADED_VALID = 'LADV_UPLOADED_VALID',
  PRACTICAL_IN_PROGRESS = 'PRACTICAL_IN_PROGRESS',
  READY_FOR_PRACTICAL_EXAM = 'READY_FOR_PRACTICAL_EXAM',
}

export type JourneyStageKey = keyof typeof JourneyStage;

export const JOURNEY_STAGE_ORDER: JourneyStage[] = [
  JourneyStage.REGISTERED,
  JourneyStage.THEORY_COURSE_IN_PROGRESS,
  JourneyStage.RENACH_PENDING,
  JourneyStage.MEDICAL_PENDING,
  JourneyStage.PSYCH_PENDING,
  JourneyStage.THEORY_EXAM_PENDING,
  JourneyStage.AWAITING_LADV_UPLOAD,
  JourneyStage.LADV_UPLOADED_VALID,
  JourneyStage.PRACTICAL_IN_PROGRESS,
  JourneyStage.READY_FOR_PRACTICAL_EXAM,
];
